In [1]:
import torch, torchinfo, torchmetrics
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt

#print(torch.randn(3,3))        just to test if pytorch is working


Introduction to Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.shape

torch.Size([])

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix[0]

tensor([7, 8])

Tensor

In [10]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.shape


torch.Size([2, 3, 3])

In [12]:
tensor[0,0,2]

tensor(3)

In [13]:
tensor[0,0]

tensor([1, 2, 3])

Random Tensors


In [14]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [15]:
random_tensor

tensor([[0.9552, 0.2272, 0.5558, 0.5090],
        [0.8084, 0.2359, 0.8812, 0.6527],
        [0.8773, 0.7760, 0.8707, 0.8808]])

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_tensor.ndim

2

In [18]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [19]:
#create tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors and tensors-like

In [21]:
#use torch.range()
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

creating tensors-like

In [22]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Changing the data type of the tensor

In [23]:
float32_tensor = torch.tensor([3,5,7],dtype = torch.float16,device="mps")

In [24]:
float32_tensor.dtype

torch.float16

In [25]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6717, 0.8370, 0.1886, 0.8938],
        [0.6616, 0.0798, 0.9745, 0.6132],
        [0.3571, 0.2403, 0.5087, 0.1598]])

In [26]:
print(some_tensor)
print(f"Some tensor dtype {some_tensor.dtype}")
print(f"Some tensor shape: {some_tensor.shape}")
print(f"Some tensor device {some_tensor.device}")


tensor([[0.6717, 0.8370, 0.1886, 0.8938],
        [0.6616, 0.0798, 0.9745, 0.6132],
        [0.3571, 0.2403, 0.5087, 0.1598]])
Some tensor dtype torch.float32
Some tensor shape: torch.Size([3, 4])
Some tensor device cpu


In [27]:
some_tensor= tensor.to('mps')

In [28]:
some_tensor.device

device(type='mps', index=0)

Tensor manipulation

In [29]:
tensor = torch.tensor([1,2,3]) 
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor

tensor([1, 2, 3])

In [31]:
tensor.ndim

1

In [32]:
tensor_rand = torch.rand(2,3)
tensor_rand

tensor([[0.4501, 0.5680, 0.3208],
        [0.5675, 0.0971, 0.4620]])

In [33]:
tensor_rand * 10

tensor([[4.5009, 5.6795, 3.2079],
        [5.6746, 0.9713, 4.6198]])

Matrix multiplication

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
torch.matmul(tensor,tensor)

tensor(14)

In [37]:
s=torch.rand(3,2)
s

tensor([[0.6166, 0.1814],
        [0.8457, 0.4609],
        [0.6394, 0.8463]])

In [38]:
m=torch.rand(2,3)
m

tensor([[0.4534, 0.6594, 0.9041],
        [0.5080, 0.7046, 0.8038]])

In [39]:
s.ndim


2

In [40]:
torch.matmul(s,m)

tensor([[0.3717, 0.5344, 0.7033],
        [0.6175, 0.8824, 1.1350],
        [0.7198, 1.0179, 1.2583]])

In [41]:
torch.mm(s,m)       #same as matmul

tensor([[0.3717, 0.5344, 0.7033],
        [0.6175, 0.8824, 1.1350],
        [0.7198, 1.0179, 1.2583]])

In [42]:
s.T


tensor([[0.6166, 0.8457, 0.6394],
        [0.1814, 0.4609, 0.8463]])

In [43]:
s

tensor([[0.6166, 0.1814],
        [0.8457, 0.4609],
        [0.6394, 0.8463]])

Finding the min, max, mean, sum ... (tensor aggregation)

In [44]:
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
y = torch.rand(2,3)
y

tensor([[0.9955, 0.2905, 0.4439],
        [0.0581, 0.7136, 0.9893]])

In [46]:
torch.min(y)

tensor(0.0581)

In [47]:
x.dtype

torch.int64

In [48]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [49]:
torch.mean(y)

tensor(0.5818)

In [50]:
y.dtype

torch.float32

In [51]:
x.sum()

tensor(450)

Position of min / max

In [52]:
x.argmin()

tensor(0)

In [53]:
y.argmin()

tensor(3)

In [54]:
y.argmax()

tensor(0)

In [55]:
z = torch.rand(3,2,4)
z

tensor([[[0.8742, 0.6852, 0.6850, 0.8624],
         [0.0500, 0.5881, 0.9144, 0.9570]],

        [[0.2369, 0.9100, 0.5916, 0.3559],
         [0.0504, 0.3938, 0.4801, 0.6645]],

        [[0.2520, 0.2383, 0.4787, 0.0522],
         [0.4576, 0.4874, 0.2842, 0.0816]]])

In [56]:
z.argmin()      #doesnt matter what dimension the tensor is 

tensor(4)

In [57]:
z[0,1,3]

tensor(0.9570)

Reshapping, stacking, squeezing and unsqueezing

In [58]:
x, x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [59]:
x_reshape = x.reshape(2,5)

In [60]:
x_reshape , x_reshape.shape

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 torch.Size([2, 5]))

In [61]:
y.shape

torch.Size([2, 3])

In [62]:
y.reshape(3,2),y

(tensor([[0.9955, 0.2905],
         [0.4439, 0.0581],
         [0.7136, 0.9893]]),
 tensor([[0.9955, 0.2905, 0.4439],
         [0.0581, 0.7136, 0.9893]]))

In [63]:
j=torch.rand(10)
j

tensor([0.6395, 0.5516, 0.4331, 0.9630, 0.1782, 0.4643, 0.9564, 0.4869, 0.4667,
        0.9207])

In [64]:
x_stacked = torch.stack([x,j])
x_stacked, x_stacked.shape

(tensor([[ 0.0000, 10.0000, 20.0000, 30.0000, 40.0000, 50.0000, 60.0000, 70.0000,
          80.0000, 90.0000],
         [ 0.6395,  0.5516,  0.4331,  0.9630,  0.1782,  0.4643,  0.9564,  0.4869,
           0.4667,  0.9207]]),
 torch.Size([2, 10]))

In [65]:
x_stacked

tensor([[ 0.0000, 10.0000, 20.0000, 30.0000, 40.0000, 50.0000, 60.0000, 70.0000,
         80.0000, 90.0000],
        [ 0.6395,  0.5516,  0.4331,  0.9630,  0.1782,  0.4643,  0.9564,  0.4869,
          0.4667,  0.9207]])

In [66]:
x_stacked.squeeze()
x_stacked.shape

torch.Size([2, 10])

In [67]:
k = torch.rand(1,2,3,4,1,6,7)
k.shape

torch.Size([1, 2, 3, 4, 1, 6, 7])

In [68]:
k = torch.squeeze(k)
k.shape

torch.Size([2, 3, 4, 6, 7])

In [69]:
k = k.unsqueeze(dim=3)
k.shape

torch.Size([2, 3, 4, 1, 6, 7])

Indexing (selecting data from tensors)

In [70]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
x[0,0]

tensor([1, 2, 3])

In [72]:
x[:,1,1]

tensor([5])

In [73]:
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch tensors & NumPy

In [74]:
#numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).to(torch.float32)
array , tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

Reproducibility

In [75]:
randomtensor1 = torch.rand(3,4)
randomtensor2 = torch.rand(3,4)

randomtensor1, randomtensor2


(tensor([[0.3742, 0.4075, 0.3650, 0.0053],
         [0.6682, 0.6215, 0.2396, 0.2572],
         [0.2414, 0.9282, 0.7599, 0.7345]]),
 tensor([[0.0341, 0.9541, 0.2652, 0.4591],
         [0.6504, 0.1856, 0.1153, 0.2346],
         [0.1342, 0.5653, 0.0694, 0.7714]]))

In [76]:
print(randomtensor1==randomtensor2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [77]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randomtensor3 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randomtensor4 =torch.rand(3,4)

In [78]:
randomtensor4 =torch.rand(3,4)

In [79]:
print(randomtensor3==randomtensor4)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Running tensors and Pytorch objects on GPUs (for faster computations)

In [80]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    print("MPS is available. GPU can be used with PyTorch on Apple Silicon.")
    
    # Optionally, you can get the MPS device name
    mps_device = torch.device("mps")
    print(f"Using device: {mps_device}")
else:
    print("MPS is not available. GPU cannot be used with PyTorch on Apple Silicon.")


MPS is available. GPU can be used with PyTorch on Apple Silicon.
Using device: mps


device agnostic code

In [81]:
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"Using device: {device}")


Using device: mps


Putting tensors/models on GPU

In [82]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor, tensor.device


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 device(type='cpu'))

In [83]:
tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device

(tensor([[1, 2, 3],
         [4, 5, 6]], device='mps:0'),
 device(type='mps', index=0))