In [3]:
import torch, torchinfo, torchmetrics
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt



#print(torch.randn(3,3))        just to test if pytorch is working


Introduction to Tensors

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix[0]

tensor([7, 8])

Tensor

In [12]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.shape


torch.Size([2, 3, 3])

In [14]:
tensor[0,0,2]

tensor(3)

In [15]:
tensor[0,0]

tensor([1, 2, 3])

Random Tensors


In [17]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [19]:
random_tensor

tensor([[0.1552, 0.2417, 0.4466, 0.6116],
        [0.5293, 0.6780, 0.9301, 0.8240],
        [0.7923, 0.1622, 0.4437, 0.8293]])

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_tensor.ndim

2

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [25]:
#create tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors and tensors-like

In [31]:
#use torch.range()
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

creating tensors-like

In [33]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Changing the data type of the tensor

In [39]:
float32_tensor = torch.tensor([3,5,7],dtype = torch.float16,device="mps")

In [36]:
float32_tensor.dtype

torch.float16