In [64]:
import torch, torchinfo, torchmetrics
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt



#print(torch.randn(3,3))        just to test if pytorch is working


Introduction to Tensors

In [65]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [66]:
scalar.item()

7

In [67]:
scalar.shape

torch.Size([])

In [68]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [69]:
vector.ndim

1

In [70]:
vector.shape

torch.Size([2])

In [71]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [72]:
matrix[0]

tensor([7, 8])

Tensor

In [73]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [74]:
tensor.shape


torch.Size([2, 3, 3])

In [75]:
tensor[0,0,2]

tensor(3)

In [76]:
tensor[0,0]

tensor([1, 2, 3])

Random Tensors


In [77]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [78]:
random_tensor

tensor([[0.9776, 0.6644, 0.4493, 0.2866],
        [0.5811, 0.9399, 0.6109, 0.2053],
        [0.7197, 0.2724, 0.1037, 0.3036]])

In [79]:
random_tensor.shape

torch.Size([3, 4])

In [80]:
random_tensor.ndim

2

In [81]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [82]:
#create tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [83]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors and tensors-like

In [84]:
#use torch.range()
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

creating tensors-like

In [85]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Changing the data type of the tensor

In [86]:
float32_tensor = torch.tensor([3,5,7],dtype = torch.float16,device="mps")

In [87]:
float32_tensor.dtype

torch.float16

In [88]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0221, 0.6371, 0.6930, 0.1790],
        [0.4330, 0.3305, 0.5502, 0.9661],
        [0.2004, 0.5698, 0.2307, 0.5395]])

In [89]:
print(some_tensor)
print(f"Some tensor dtype {some_tensor.dtype}")
print(f"Some tensor shape: {some_tensor.shape}")
print(f"Some tensor device {some_tensor.device}")


tensor([[0.0221, 0.6371, 0.6930, 0.1790],
        [0.4330, 0.3305, 0.5502, 0.9661],
        [0.2004, 0.5698, 0.2307, 0.5395]])
Some tensor dtype torch.float32
Some tensor shape: torch.Size([3, 4])
Some tensor device cpu


In [90]:
some_tensor= tensor.to('mps')

In [91]:
some_tensor.device

device(type='mps', index=0)

Tensor manipulation

In [92]:
tensor = torch.tensor([1,2,3]) 
tensor + 10

tensor([11, 12, 13])

In [93]:
tensor

tensor([1, 2, 3])

In [94]:
tensor.ndim

1

In [95]:
tensor_rand = torch.rand(2,3)
tensor_rand

tensor([[0.3277, 0.0999, 0.3882],
        [0.9375, 0.3714, 0.2411]])

In [96]:
tensor_rand * 10

tensor([[3.2772, 0.9986, 3.8821],
        [9.3749, 3.7139, 2.4114]])

Matrix multiplication

In [97]:
tensor

tensor([1, 2, 3])

In [98]:
tensor * tensor

tensor([1, 4, 9])

In [99]:
torch.matmul(tensor,tensor)

tensor(14)

In [100]:
s=torch.rand(3,2)
s

tensor([[0.2269, 0.0673],
        [0.6808, 0.7058],
        [0.9115, 0.9900]])

In [101]:
m=torch.rand(2,3)
m

tensor([[0.9970, 0.4536, 0.7228],
        [0.7989, 0.2559, 0.7015]])

In [102]:
s.ndim


2

In [103]:
torch.matmul(s,m)

tensor([[0.2800, 0.1201, 0.2112],
        [1.2427, 0.4894, 0.9873],
        [1.6997, 0.6668, 1.3534]])

In [104]:
torch.mm(s,m)       #same as matmul

tensor([[0.2800, 0.1201, 0.2112],
        [1.2427, 0.4894, 0.9873],
        [1.6997, 0.6668, 1.3534]])

In [105]:
s.T


tensor([[0.2269, 0.6808, 0.9115],
        [0.0673, 0.7058, 0.9900]])

In [106]:
s

tensor([[0.2269, 0.0673],
        [0.6808, 0.7058],
        [0.9115, 0.9900]])

Finding the min, max, mean, sum ... (tensor aggregation)

In [132]:
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
y = torch.rand(2,3)
y

tensor([[0.6461, 0.5494, 0.1413],
        [0.6640, 0.0110, 0.2946]])

In [134]:
torch.min(y)

tensor(0.0110)

In [135]:
x.dtype

torch.int64

In [136]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [137]:
torch.mean(y)

tensor(0.3844)

In [138]:
y.dtype

torch.float32

In [139]:
x.sum()

tensor(450)

Position of min / max

In [140]:
x.argmin()

tensor(0)

In [141]:
y.argmin()

tensor(4)

In [142]:
y.argmax()

tensor(3)

In [143]:
z = torch.rand(3,2,4)
z

tensor([[[0.8485, 0.8436, 0.6849, 0.9743],
         [0.4434, 0.1580, 0.7588, 0.0146]],

        [[0.0515, 0.1537, 0.0151, 0.7672],
         [0.5677, 0.3983, 0.9786, 0.9458]],

        [[0.0674, 0.1090, 0.4529, 0.7911],
         [0.5631, 0.7071, 0.2583, 0.2686]]])

In [144]:
z.argmin()      #doesnt matter what dimension the tensor is 

tensor(7)

In [149]:
z[0,1,3]

tensor(0.0146)

Reshapping, stacking, squeezing and unsqueezing

In [151]:
x, x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [152]:
x_reshape = x.reshape(2,5)

In [154]:
x_reshape , x_reshape.shape

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 torch.Size([2, 5]))

In [156]:
y.shape

torch.Size([2, 3])

In [158]:
y.reshape(3,2),y

(tensor([[0.6461, 0.5494],
         [0.1413, 0.6640],
         [0.0110, 0.2946]]),
 tensor([[0.6461, 0.5494, 0.1413],
         [0.6640, 0.0110, 0.2946]]))

In [169]:
j=torch.rand(10)
j

tensor([0.5577, 0.6042, 0.2634, 0.4697, 0.5454, 0.8593, 0.9793, 0.9630, 0.8462,
        0.6670])

In [189]:
x_stacked = torch.stack([x,j])
x_stacked, x_stacked.shape

(tensor([[ 0.0000, 10.0000, 20.0000, 30.0000, 40.0000, 50.0000, 60.0000, 70.0000,
          80.0000, 90.0000],
         [ 0.5577,  0.6042,  0.2634,  0.4697,  0.5454,  0.8593,  0.9793,  0.9630,
           0.8462,  0.6670]]),
 torch.Size([2, 10]))

In [190]:
x_stacked

tensor([[ 0.0000, 10.0000, 20.0000, 30.0000, 40.0000, 50.0000, 60.0000, 70.0000,
         80.0000, 90.0000],
        [ 0.5577,  0.6042,  0.2634,  0.4697,  0.5454,  0.8593,  0.9793,  0.9630,
          0.8462,  0.6670]])

In [191]:
x_stacked.squeeze()
x_stacked.shape

torch.Size([2, 10])

In [207]:
k = torch.rand(1,2,3,4,1,6,7)
k.shape

torch.Size([1, 2, 3, 4, 1, 6, 7])

In [208]:
k = torch.squeeze(k)
k.shape

torch.Size([2, 3, 4, 6, 7])

In [210]:
k = k.unsqueeze(dim=3)
k.shape

torch.Size([1, 2, 3, 1, 4, 6, 7])