In [3]:
import torch, torchinfo, torchmetrics
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt



#print(torch.randn(3,3))        just to test if pytorch is working


Introduction to Tensors

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix[0]

tensor([7, 8])

Tensor

In [12]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.shape


torch.Size([2, 3, 3])

In [14]:
tensor[0,0,2]

tensor(3)

In [15]:
tensor[0,0]

tensor([1, 2, 3])

Random Tensors


In [17]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [19]:
random_tensor

tensor([[0.1552, 0.2417, 0.4466, 0.6116],
        [0.5293, 0.6780, 0.9301, 0.8240],
        [0.7923, 0.1622, 0.4437, 0.8293]])

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_tensor.ndim

2

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [25]:
#create tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors and tensors-like

In [31]:
#use torch.range()
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

creating tensors-like

In [33]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Changing the data type of the tensor

In [39]:
float32_tensor = torch.tensor([3,5,7],dtype = torch.float16,device="mps")

In [36]:
float32_tensor.dtype

torch.float16

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4985, 0.8290, 0.4787, 0.9254],
        [0.2981, 0.1086, 0.8300, 0.0187],
        [0.2335, 0.5635, 0.1246, 0.6034]])

In [43]:
print(some_tensor)
print(f"Some tensor dtype {some_tensor.dtype}")
print(f"Some tensor shape: {some_tensor.shape}")
print(f"Some tensor device {some_tensor.device}")


tensor([[0.4985, 0.8290, 0.4787, 0.9254],
        [0.2981, 0.1086, 0.8300, 0.0187],
        [0.2335, 0.5635, 0.1246, 0.6034]])
Some tensor dtype torch.float32
Some tensor shape: torch.Size([3, 4])
Some tensor device cpu


In [56]:
some_tensor= tensor.to('mps')

In [57]:
some_tensor.device

device(type='mps', index=0)

Tensor manipulation

In [58]:
tensor = torch.tensor([1,2,3]) 
tensor + 10

tensor([11, 12, 13])

In [59]:
tensor

tensor([1, 2, 3])

In [61]:
tensor.ndim

1

In [64]:
tensor_rand = torch.rand(2,3)
tensor_rand

tensor([[0.2076, 0.0771, 0.3535],
        [0.0997, 0.8612, 0.8882]])

In [66]:
tensor_rand * 10

tensor([[2.0765, 0.7708, 3.5350],
        [0.9974, 8.6116, 8.8821]])