In [212]:
import torch, torchinfo, torchmetrics
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt

#print(torch.randn(3,3))        just to test if pytorch is working


Introduction to Tensors

In [213]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [214]:
scalar.item()

7

In [215]:
scalar.shape

torch.Size([])

In [216]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [217]:
vector.ndim

1

In [218]:
vector.shape

torch.Size([2])

In [219]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [220]:
matrix[0]

tensor([7, 8])

Tensor

In [221]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [222]:
tensor.shape


torch.Size([2, 3, 3])

In [223]:
tensor[0,0,2]

tensor(3)

In [224]:
tensor[0,0]

tensor([1, 2, 3])

Random Tensors


In [225]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [226]:
random_tensor

tensor([[0.4926, 0.6520, 0.7569, 0.7436],
        [0.9948, 0.4650, 0.4644, 0.4102],
        [0.6615, 0.2433, 0.4082, 0.4999]])

In [227]:
random_tensor.shape

torch.Size([3, 4])

In [228]:
random_tensor.ndim

2

In [229]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [230]:
#create tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [231]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors and tensors-like

In [232]:
#use torch.range()
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

creating tensors-like

In [233]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Changing the data type of the tensor

In [234]:
float32_tensor = torch.tensor([3,5,7],dtype = torch.float16,device="mps")

In [235]:
float32_tensor.dtype

torch.float16

In [236]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[2.9111e-04, 6.2736e-01, 8.7778e-01, 6.9840e-01],
        [5.6474e-01, 1.2710e-01, 3.9818e-01, 5.6657e-01],
        [4.0899e-02, 3.7801e-01, 6.1041e-01, 4.2505e-01]])

In [237]:
print(some_tensor)
print(f"Some tensor dtype {some_tensor.dtype}")
print(f"Some tensor shape: {some_tensor.shape}")
print(f"Some tensor device {some_tensor.device}")


tensor([[2.9111e-04, 6.2736e-01, 8.7778e-01, 6.9840e-01],
        [5.6474e-01, 1.2710e-01, 3.9818e-01, 5.6657e-01],
        [4.0899e-02, 3.7801e-01, 6.1041e-01, 4.2505e-01]])
Some tensor dtype torch.float32
Some tensor shape: torch.Size([3, 4])
Some tensor device cpu


In [238]:
some_tensor= tensor.to('mps')

In [239]:
some_tensor.device

device(type='mps', index=0)

Tensor manipulation

In [240]:
tensor = torch.tensor([1,2,3]) 
tensor + 10

tensor([11, 12, 13])

In [241]:
tensor

tensor([1, 2, 3])

In [242]:
tensor.ndim

1

In [243]:
tensor_rand = torch.rand(2,3)
tensor_rand

tensor([[0.5716, 0.1284, 0.7114],
        [0.2705, 0.4347, 0.3594]])

In [244]:
tensor_rand * 10

tensor([[5.7156, 1.2840, 7.1140],
        [2.7045, 4.3465, 3.5936]])

Matrix multiplication

In [245]:
tensor

tensor([1, 2, 3])

In [246]:
tensor * tensor

tensor([1, 4, 9])

In [247]:
torch.matmul(tensor,tensor)

tensor(14)

In [248]:
s=torch.rand(3,2)
s

tensor([[0.0387, 0.0912],
        [0.4552, 0.7244],
        [0.6446, 0.2782]])

In [249]:
m=torch.rand(2,3)
m

tensor([[0.1129, 0.1770, 0.6021],
        [0.3190, 0.9711, 0.6358]])

In [250]:
s.ndim


2

In [251]:
torch.matmul(s,m)

tensor([[0.0334, 0.0954, 0.0813],
        [0.2825, 0.7840, 0.7346],
        [0.1615, 0.3842, 0.5650]])

In [252]:
torch.mm(s,m)       #same as matmul

tensor([[0.0334, 0.0954, 0.0813],
        [0.2825, 0.7840, 0.7346],
        [0.1615, 0.3842, 0.5650]])

In [253]:
s.T


tensor([[0.0387, 0.4552, 0.6446],
        [0.0912, 0.7244, 0.2782]])

In [254]:
s

tensor([[0.0387, 0.0912],
        [0.4552, 0.7244],
        [0.6446, 0.2782]])

Finding the min, max, mean, sum ... (tensor aggregation)

In [255]:
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [256]:
y = torch.rand(2,3)
y

tensor([[0.5931, 0.0813, 0.3999],
        [0.6543, 0.6719, 0.0519]])

In [257]:
torch.min(y)

tensor(0.0519)

In [258]:
x.dtype

torch.int64

In [259]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [260]:
torch.mean(y)

tensor(0.4087)

In [261]:
y.dtype

torch.float32

In [262]:
x.sum()

tensor(450)

Position of min / max

In [263]:
x.argmin()

tensor(0)

In [264]:
y.argmin()

tensor(5)

In [265]:
y.argmax()

tensor(4)

In [266]:
z = torch.rand(3,2,4)
z

tensor([[[0.5378, 0.8506, 0.8817, 0.7025],
         [0.6267, 0.3543, 0.9838, 0.6675]],

        [[0.9561, 0.6631, 0.7725, 0.3870],
         [0.3483, 0.7457, 0.4713, 0.9186]],

        [[0.1203, 0.7826, 0.6692, 0.1217],
         [0.9321, 0.5989, 0.8668, 0.0063]]])

In [267]:
z.argmin()      #doesnt matter what dimension the tensor is 

tensor(23)

In [268]:
z[0,1,3]

tensor(0.6675)

Reshapping, stacking, squeezing and unsqueezing

In [269]:
x, x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [270]:
x_reshape = x.reshape(2,5)

In [271]:
x_reshape , x_reshape.shape

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 torch.Size([2, 5]))

In [272]:
y.shape

torch.Size([2, 3])

In [273]:
y.reshape(3,2),y

(tensor([[0.5931, 0.0813],
         [0.3999, 0.6543],
         [0.6719, 0.0519]]),
 tensor([[0.5931, 0.0813, 0.3999],
         [0.6543, 0.6719, 0.0519]]))

In [274]:
j=torch.rand(10)
j

tensor([0.2302, 0.5125, 0.5321, 0.8645, 0.4909, 0.5003, 0.5850, 0.0221, 0.9835,
        0.9562])

In [275]:
x_stacked = torch.stack([x,j])
x_stacked, x_stacked.shape

(tensor([[0.0000e+00, 1.0000e+01, 2.0000e+01, 3.0000e+01, 4.0000e+01, 5.0000e+01,
          6.0000e+01, 7.0000e+01, 8.0000e+01, 9.0000e+01],
         [2.3015e-01, 5.1247e-01, 5.3207e-01, 8.6447e-01, 4.9087e-01, 5.0033e-01,
          5.8498e-01, 2.2064e-02, 9.8349e-01, 9.5619e-01]]),
 torch.Size([2, 10]))

In [276]:
x_stacked

tensor([[0.0000e+00, 1.0000e+01, 2.0000e+01, 3.0000e+01, 4.0000e+01, 5.0000e+01,
         6.0000e+01, 7.0000e+01, 8.0000e+01, 9.0000e+01],
        [2.3015e-01, 5.1247e-01, 5.3207e-01, 8.6447e-01, 4.9087e-01, 5.0033e-01,
         5.8498e-01, 2.2064e-02, 9.8349e-01, 9.5619e-01]])

In [277]:
x_stacked.squeeze()
x_stacked.shape

torch.Size([2, 10])

In [278]:
k = torch.rand(1,2,3,4,1,6,7)
k.shape

torch.Size([1, 2, 3, 4, 1, 6, 7])

In [279]:
k = torch.squeeze(k)
k.shape

torch.Size([2, 3, 4, 6, 7])

In [280]:
k = k.unsqueeze(dim=3)
k.shape

torch.Size([2, 3, 4, 1, 6, 7])

Indexing (selecting data from tensors)

In [284]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [286]:
x[0,0]

tensor([1, 2, 3])

In [287]:
x[:,1,1]

tensor([5])

In [288]:
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch tensors & NumPy

In [290]:
#numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).to(torch.float32)
array , tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

Reproducibility

In [292]:
randomtensor1 = torch.rand(3,4)
randomtensor2 = torch.rand(3,4)

randomtensor1, randomtensor2


(tensor([[0.4019, 0.1876, 0.2942, 0.8129],
         [0.3445, 0.1311, 0.4529, 0.0382],
         [0.7413, 0.6949, 0.8327, 0.8985]]),
 tensor([[0.7962, 0.7496, 0.5320, 0.2923],
         [0.4363, 0.0046, 0.5182, 0.8888],
         [0.4187, 0.2256, 0.3066, 0.1303]]))

In [293]:
print(randomtensor1==randomtensor2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [295]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randomtensor3 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randomtensor4 =torch.rand(3,4)

In [ ]:
randomtensor4 =torch.rand(3,4)

In [296]:
print(randomtensor3==randomtensor4)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and Pytorch objects on GPUs (for faster computations)

In [298]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    print("MPS is available. GPU can be used with PyTorch on Apple Silicon.")
    
    # Optionally, you can get the MPS device name
    mps_device = torch.device("mps")
    print(f"Using device: {mps_device}")
else:
    print("MPS is not available. GPU cannot be used with PyTorch on Apple Silicon.")


MPS is available. GPU can be used with PyTorch on Apple Silicon.
Using device: mps


device agnostic code

In [302]:
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"Using device: {device}")


Using device: mps


Putting tensors/models on GPU

In [304]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor, tensor.device


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 device(type='cpu'))

In [306]:
tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device

(tensor([[1, 2, 3],
         [4, 5, 6]], device='mps:0'),
 device(type='mps', index=0))